install.packages("tidyverse")
install.packages("usdata")
install.packages("ggthemes")
install.packages("viridis")
install.packages("class")
install.packages("caret")

library(class)
library(caret)
library(e1071)
library(viridis)
library(ggthemes)
library(usdata)
library(tidyverse)
library(dplyr)
library(sqldf)